### ISSUE TITLE
Any Dungeons Guide Menu will cause Minecraft Vanilla GUIs to behave differently

### ISSUE THREAD

**Issue by My-Name-Is-Jeff** [cyoung06/Skyblock-Dungeons-Guide#1]
Steps to reproduce:

1. Open the Dungeons Guide Config menu
2. Hotbar and other parts of the GuiIngame will display different, including flashing

**Comment by cyoung06** [comment]
Does not happen in dev env.

Seems to be mod conflict.

**Comment by koxx12-dev** [comment]
@cyoung06 i think you should unpin it
