### ISSUE TITLE
Unable to authenticate 

### ISSUE THREAD

**Issue by EP1812** [cyoung06/Skyblock-Dungeons-Guide#10]
Was not able to authenticate dungeons guide using forge launcher. I tried logging out of mojang accounts and reinstalling the mod, but the same error keeps occurring. In the error report, it gives 
States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
UCE	skyblock_dungeons_guide{1.0} [Skyblock Dungeons Guide] (dungeonsguide-3.0.jar) 
Edit: all other mods loaded are working fine

**Comment by riohorealhk** [comment]
fixed, @cyoung06 please close issue

**Comment by Enderboyscool** [comment]
If the server is down this will happen they forgot to say this when you crash so don't worry

**Comment by ItIsBanana** [comment]
> Was not able to authenticate dungeons guide using forge launcher. I tried logging out of mojang accounts and reinstalling the mod, but the same error keeps occurring. In the error report, it gives
> States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
> UCE skyblock_dungeons_guide{1.0} [Skyblock Dungeons Guide] (dungeonsguide-3.0.jar)
> Edit: all other mods loaded are working fine

Same for me. It isn't fixed. Unable to authenticate

**Comment by Shxxd0w** [comment]
Also same for me.

**Comment by cyoung06** [comment]
Should be fixed in a release that will be released today.
