### ISSUE TITLE
Profit Calculator

### ISSUE THREAD

**Issue by WatchDawq** [cyoung06/Skyblock-Dungeons-Guide#16]
The dungeons profit thing from the chests are just showing there ah prices and not bin and some of them are way of on there profit

**Comment by GraczBezNicku** [comment]
Ye that sucks, I recommend enabling the NEU profit. It will go by lowest BIN.

**Comment by cyoung06** [comment]
DG Lowest Bin is actually lowest bin

it is just that it is "GLOBAL" lowest bin, meaning it will show the lowest price dg server has seen it sell for.

If dg server has seen a necron handle being sold for 1m, it will display lowest bin as 1m

Anyways use neu profit, it's way better
