### ISSUE TITLE
Giving this error

### ISSUE THREAD

**Issue by NoOdLeTamircilik** [cyoung06/Skyblock-Dungeons-Guide#19]
![resim_2021-06-07_160150](https://user-images.githubusercontent.com/54625522/121021074-ab2a2b00-c7a9-11eb-9d02-081bda38a033.png)

**Comment by cyoung06** [comment]
#known-bugs-and-conflicts
https://discord.com/channels/781913473872560189/847790384515645451/848149396276641831

**Comment by NoOdLeTamircilik** [comment]
but i cant get access to server
