### ISSUE TITLE
it broke

### ISSUE THREAD

**Issue by XscopeX** [cyoung06/Skyblock-Dungeons-Guide#23]
It just stopped working the /pv works and the /dg but the guide line is gone and the score board is gone nothing from the mod works after entering a dungeon.
im on latest version
I have 
Skyblock addons
Skyblock extras
Patcher
Optifine
NEU
dungeonguide
Dungeon_rooms

**Comment by cyoung06** [comment]
1. Please use support channel in discord
2. Disable sbe's disable armorstand
