### ISSUE TITLE
Someone forgot to add "key.categories.dungeonsguide" to lang files

### ISSUE THREAD

**Issue by koxx12-dev** [cyoung06/Skyblock-Dungeons-Guide#5]
![image](https://user-images.githubusercontent.com/80456351/117548843-5de65c80-b037-11eb-9307-34861d3356dd.png)

**Comment by koxx12-dev** [comment]
wrong img

**Comment by koxx12-dev** [comment]
![image](https://user-images.githubusercontent.com/80456351/117548846-60e14d00-b037-11eb-9d19-8b6f3b2520c8.png)

**Comment by Enderboyscool** [comment]
oh its ok if it does not effect the mod
